version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=${NODE_ENV:-development}
    container_name: vega_show_app
    ports:
      - "5000:5000"
    env_file:
      - environments/.local.env
    environment:
      - PORT=5000
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
      - node_modules:/app/node_modules
    networks:
      - vega_network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    command: sh -c "npm run dev"

networks:
  vega_network:
    driver: bridge

volumes:
  node_modules: